global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "product-service"
    static_configs:
      - targets: ["productservice:9090"]
  - job_name: "cart-service"
    static_configs:
      - targets: ["localhost:9091"]
